### check home
GET http://localhost:8080

### Insert Book
POST http://localhost:8080/api/v1/books/
Content-Type: application/json

{
  "author": "Karlson",
  "title": "Life as me"
}


### Find all
GET http://localhost:8080/api/v1/books/


### Find One
GET http://localhost:8080/api/v1/books/2


### Delete by id
DELETE http://localhost:8080/api/v1/books/202


### Update a book
PUT http://localhost:8080/api/v1/books/
Content-Type: application/json

{
  "id": 2,
  "author": "K Karlson",
  "title": "Life as me second edition"
}